# TrustTunnelClientWindows CMake package config
# This file is consumed by find_package(TrustTunnelClientWindows) or via FetchContent.
#
# Provided targets:
#   TrustTunnelClientWindows::trusttunnel               - Shared library (DLL) for VPN adapter API
#   TrustTunnelClientWindows::trusttunnel_service       - Executable for VPN Windows service
#   TrustTunnelClientWindows::trusttunnel_service_installer - Elevated helper for installing/uninstalling VPN service
#
# Provided functions:
#   trusttunnel_stage_runtime(<dir> <out_var> <strip_signatures>) - Stage the runtime binaries for a consumer build
#
# The shared library (trusttunnel.dll) contains all transitive dependencies
# linked in at build time — the consumer does not need to provide any
# third-party libs.  At link time, only the import library (trusttunnel.lib)
# is needed.  At runtime, trusttunnel.dll must be on the DLL search path
# (e.g., next to the executable).
#
# Usage:
#   find_package(TrustTunnelClientWindows REQUIRED)
#   target_link_libraries(myapp PRIVATE TrustTunnelClientWindows::trusttunnel)

# Resolve all paths relative to this config file's location.
# The layout is: <prefix>/lib/cmake/TrustTunnelClientWindows/TrustTunnelClientWindowsConfig.cmake
set(_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../../..")

# --- TrustTunnelClientWindows::trusttunnel (shared library) ---
if(NOT TARGET TrustTunnelClientWindows::trusttunnel)
    add_library(TrustTunnelClientWindows::trusttunnel SHARED IMPORTED)
    set_target_properties(TrustTunnelClientWindows::trusttunnel PROPERTIES
        IMPORTED_LOCATION "${_INSTALL_PREFIX}/bin/trusttunnel.dll"
        IMPORTED_IMPLIB "${_INSTALL_PREFIX}/lib/trusttunnel.lib"
        INTERFACE_INCLUDE_DIRECTORIES "${_INSTALL_PREFIX}/include"
    )
endif()

# --- TrustTunnelClientWindows::trusttunnel_service (executable) ---
if(NOT TARGET TrustTunnelClientWindows::trusttunnel_service)
    add_executable(TrustTunnelClientWindows::trusttunnel_service IMPORTED)
    set_target_properties(TrustTunnelClientWindows::trusttunnel_service PROPERTIES
        IMPORTED_LOCATION "${_INSTALL_PREFIX}/bin/trusttunnel_service.exe"
    )
endif()

# --- TrustTunnelClientWindows::trusttunnel_service_installer (executable) ---
if(NOT TARGET TrustTunnelClientWindows::trusttunnel_service_installer)
    add_executable(TrustTunnelClientWindows::trusttunnel_service_installer IMPORTED)
    set_target_properties(TrustTunnelClientWindows::trusttunnel_service_installer PROPERTIES
        IMPORTED_LOCATION "${_INSTALL_PREFIX}/bin/trusttunnel_service_installer.exe"
    )
endif()

# --- trusttunnel_stage_runtime(<dir> <out_var> <strip_signatures>) ---
#
# Stage the runtime binaries for a consumer build: copy trusttunnel.dll, trusttunnel_service.exe,
# trusttunnel_service_installer.exe, and wintun.dll from the package's bin/ into <dir> at build
# time, set <out_var> in the caller's scope to the copies, and create the trusttunnel_runtime
# target that produces them.
#
# When <strip_signatures> is true, the embedded Authenticode signature is removed from the three
# adapter binaries with `signtool remove /s`, so that a locally built (unsigned) client is
# accepted by the service: signature binding is skipped when the service image is unsigned.
# wintun.dll keeps WireGuard's signature and is never part of the check. An already unsigned input
# is copied without error.
#
# signtool is run by name at build time. The Visual Studio generator puts the Windows SDK on the
# PATH of custom commands, and so does a developer command prompt for other generators.
set_property(GLOBAL PROPERTY _TRUSTTUNNEL_BIN_DIR "${_INSTALL_PREFIX}/bin")

function(trusttunnel_stage_runtime STAGE_DIR OUT_VAR STRIP_SIGNATURES)
    if(TARGET trusttunnel_runtime)
        message(FATAL_ERROR "trusttunnel_stage_runtime() may only be called once")
    endif()

    get_property(_bin_dir GLOBAL PROPERTY _TRUSTTUNNEL_BIN_DIR)

    if(NOT IS_ABSOLUTE "${STAGE_DIR}")
        set(STAGE_DIR "${CMAKE_CURRENT_BINARY_DIR}/${STAGE_DIR}")
    endif()

    set(_strip_script "${CMAKE_BINARY_DIR}/trusttunnel_strip_signature.cmake")
    file(GENERATE OUTPUT "${_strip_script}" CONTENT [==[
# Generated by TrustTunnelClientWindowsConfig.cmake: remove the embedded Authenticode signature
# from FILE. signtool exits non-zero when a file has no embedded signature, which is expected for
# an unsigned package and is not an error.
execute_process(
    COMMAND signtool remove /s "${FILE}"
    RESULT_VARIABLE _result
    OUTPUT_QUIET
    ERROR_QUIET
)
if(NOT _result MATCHES "^[0-9]+$")
    message(FATAL_ERROR "Failed to run signtool (${_result}). Install the Windows SDK and build with "
        "the Visual Studio generator or from a developer command prompt.")
endif()
if(NOT _result EQUAL 0)
    message(STATUS "No embedded signature removed from ${FILE} (signtool exit ${_result})")
endif()
]==])

    set(_staged)
    foreach(_name IN ITEMS trusttunnel.dll trusttunnel_service.exe trusttunnel_service_installer.exe wintun.dll)
        set(_source "${_bin_dir}/${_name}")
        set(_target "${STAGE_DIR}/${_name}")
        if(NOT EXISTS "${_source}")
            message(FATAL_ERROR "trusttunnel_stage_runtime: ${_source} does not exist")
        endif()
        set(_commands COMMAND ${CMAKE_COMMAND} -E copy "${_source}" "${_target}")
        set(_comment "Staging ${_name}")
        if(STRIP_SIGNATURES AND NOT _name STREQUAL "wintun.dll")
            list(APPEND _commands COMMAND ${CMAKE_COMMAND} "-DFILE=${_target}" -P "${_strip_script}")
            set(_comment "Staging ${_name} (signature stripped)")
        endif()
        add_custom_command(
            OUTPUT "${_target}"
            ${_commands}
            DEPENDS "${_source}"
            COMMENT "${_comment}"
            VERBATIM
        )
        list(APPEND _staged "${_target}")
    endforeach()
    add_custom_target(trusttunnel_runtime DEPENDS ${_staged})

    set(${OUT_VAR} ${_staged} PARENT_SCOPE)
endfunction()
