name: Upload conan recipes

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - After auto-tag

jobs:
  upload-conan-recipes:
    name: Upload conan recipes
    if: github.repository == 'AdGuardSoftwareLimited/trusttunnel-client'
    environment: conan-artifactory
    runs-on: [team-corelibs]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Upload conan recipes
        uses: AdGuardSoftwareLimited/native-libs-common/.github/actions/upload-conan-recipes@master
        with:
          export_script_path: scripts/export_conan.sh
          conan_repo_url: ${{ vars.CONAN_REPO_URL }}
          artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
          artifactory_api_key: ${{ secrets.ARTIFACTORY_API_KEY }}
